spring:
  application:
    name: test-23
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  logging:                                # 配置日志级别，让hibernate打印出执行的SQL
    level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
  eureka:
    client:
      serviceUrl:
        defaultZone: http://47.98.191.46:8761/eureka/
    instance:
      prefer-ip-address: true
server:
  port: 9090