server:
  port: 8000
spring:
  application:
    name: microservice-provider-user
#  datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://47.98.191.46:3306/demo
#        username: root
#        password: 123456
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.98.191.46:3306/demo
      username: root
      password: 123456
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.98.191.46:3306/demo1
      username: root
      password: 123456


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.98.191.46:8761/eureka/
  instance:
    prefer-ip-address: true